service: nestmonolith

plugins:
  - serverless-jetpack
  - serverless-offline
 
provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  memorySize: 2048
  timeout: 20
  stage: "dev" #prefix "dev" if undefined
  environment:
    MY_ENV_VAR: 'MY VALUE'
    USERS_TABLE_NAME: ${self:custom.usersTable.name}
    
  iamRoleStatements: ${file(iam/usersTableIAM.yml)}



functions:
  main: # The name of the lambda function
    # The module 'handler' is exported in the file 'src/lambda'
    handler: dist/lambda.handler
    description: Nestjs backend
    events:
      - http:
         method: any
         path: /{any+}

         

resources:
  Resources:
    usersTable: ${file(resources/usersTable.yml):usersTable}



        


custom:
  usersTable:
    name: ${self:provider.stage}-users
    arn: !GetAtt usersTable.Arn

